apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics-collector
  template:
    metadata:
      labels:
        app: metrics-collector
    spec:
      containers:
      - name: metrics-collector
        image: arya6296/metrics_collector:v1
        ports:
        - containerPort: 7878
---
apiVersion: v1
kind: Service
metadata:
  name: metrics-collector-service
spec:
  type: NodePort
  ports:
  - port: 7878
    nodePort: 30003
    targetPort: 7878
  selector:
    app: metrics-collector

